CREATE TABLE drones
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    status    VARCHAR(255),
    createdAt TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_drones PRIMARY KEY (id)
);

CREATE TABLE missions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operatorId BIGINT,
    droneId    BIGINT,
    latitude   FLOAT,
    longitude  FLOAT,
    createdAt  TIMESTAMP WITHOUT TIME ZONE,
    startedAt  TIMESTAMP WITHOUT TIME ZONE,
    probeAt    TIMESTAMP WITHOUT TIME ZONE,
    finishedAt TIMESTAMP WITHOUT TIME ZONE,
    resultId   BIGINT,
    CONSTRAINT pk_missions PRIMARY KEY (id)
);

CREATE TABLE operators
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255),
    password  VARCHAR(255),
    createdAt TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_operators PRIMARY KEY (id)
);

CREATE TABLE results
(
    missionId    BIGINT NOT NULL,
    pH           FLOAT,
    dissolvedoxygen         FLOAT,
    temp         FLOAT,
    turbidity    FLOAT,
    conductivity FLOAT,
    probeReport  VARCHAR(255),
    createdAt    TIMESTAMP WITHOUT TIME ZONE,
    reportAt     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_results PRIMARY KEY (missionId)
);

CREATE TABLE telemetries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    missionId    BIGINT,
    droneId      BIGINT,
    createdAt    TIMESTAMP WITHOUT TIME ZONE,
    batteryLevel FLOAT,
    altitude     FLOAT,
    speed        FLOAT,
    latitude     FLOAT,
    longitude    FLOAT,
    thrust       FLOAT,
    roll         FLOAT,
    pitch        FLOAT,
    yaw          FLOAT,
    CONSTRAINT pk_telemetries PRIMARY KEY (id)
);

ALTER TABLE missions
    ADD CONSTRAINT uc_missions_resultid UNIQUE (resultId);

ALTER TABLE missions
    ADD CONSTRAINT FK_MISSIONS_ON_DRONEID FOREIGN KEY (droneId) REFERENCES drones (id);

ALTER TABLE missions
    ADD CONSTRAINT FK_MISSIONS_ON_OPERATORID FOREIGN KEY (operatorId) REFERENCES operators (id);

ALTER TABLE missions
    ADD CONSTRAINT FK_MISSIONS_ON_RESULTID FOREIGN KEY (resultId) REFERENCES results (missionId);

ALTER TABLE results
    ADD CONSTRAINT FK_RESULTS_ON_MISSIONID FOREIGN KEY (missionId) REFERENCES missions (id);

ALTER TABLE telemetries
    ADD CONSTRAINT FK_TELEMETRIES_ON_DRONEID FOREIGN KEY (droneId) REFERENCES drones (id);

ALTER TABLE telemetries
    ADD CONSTRAINT FK_TELEMETRIES_ON_MISSIONID FOREIGN KEY (missionId) REFERENCES missions (id);